### ISSUE TITLE
Google discontinuing Google Trusted Stores and changing to Google Reviews

### ISSUE THREAD

**Issue by MisterHoudini** [iansvo/monstercommerce-snippets#3]
#### Order Confirmation Page Code  as provide by Google for new Google Reviews #### 

```
<script src="https://apis.google.com/js/platform.js?onload=renderOptIn" async defer></script>

<script>
  window.renderOptIn = function() {
    window.gapi.load('surveyoptin', function() {
      window.gapi.surveyoptin.render(
        {
          "merchant_id": 0000000,
          "order_id": "ORDER_ID",
          "email": "CUSTOMER_EMAIL",
          "delivery_country": "COUNTRY_CODE",
          "estimated_delivery_date": "YYYY-MM-DD"
        });
    });
  }
</script>
```

For the 5 variables, I of course have the merchant_id, and can hard code that.
I believe I can just use 
%Order.Number% in place of ORDER_ID
and
%Customer.Email% in place of CUSTOMER_EMAIL
(but if not, need help with these also).
And really need a bit of help getting the bits of old GTS code for the delivery_country and estimated_delivery_date.

Integration guide is here https://support.google.com/merchants/answer/7106244?hl=en

btw, are you still at NetSol? 

Cheers,
Dave

**Comment by iansvo** [comment]
Dave,

Thanks for writing your issue. I stopped working at Web.com in April 2016. 

Ultimately this looks pretty simple to me. You appear to be on track with the nsScript variables in question (%Order.Number%, and %Customer.Email%).

For the other items....

"delivery_country" should be "US", since I presume you're still shipping from the US.

"estimated_delivery_date" is a bit tricky though, since you'll need to specify a date and nsScripts don't really provide an option for this. This type of thing is going to require doing some more advanced custom coding, but the original example I used could be adapted to provide the date details. 

My suggestion would be to pursue some custom development work via Web.com, if they have a qualified person who can do so. I imagine someone there should be able to help you with that.
